apiVersion: v1
kind: Service
metadata:
  name: {{ include "govwatch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "govwatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    {{- include "govwatch.workerSelectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
